# Generated by Django 6.0.7 on 2026-07-13 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0002_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('BUY', 'خرید'), ('SELL', 'فروش'), ('EXCHANGE', 'چنج')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=15)),
                ('tracking_number', models.CharField(max_length=100, unique=True)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchange.customer')),
                ('from_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_transactions', to='exchange.currency')),
                ('to_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_transactions', to='exchange.currency')),
            ],
        ),
    ]
