# Generated by Django 6.0.7 on 2026-07-13 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0005_wallet'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchange.currency')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchange.wallet')),
            ],
            options={
                'verbose_name': 'موجودی کیف پول',
                'verbose_name_plural': 'موجودی کیف پول\u200cها',
            },
        ),
    ]
