# Generated by Django 6.0.7 on 2026-07-13 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0006_walletbalance'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchange.currency')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchange.customer')),
            ],
            options={
                'verbose_name': 'گردش حساب',
                'verbose_name_plural': 'گردش حساب\u200cها',
            },
        ),
    ]
