# Generated by Django 6.0.7 on 2026-07-14 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0008_transaction_from_wallet_transaction_to_wallet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='created_at',
        ),
        migrations.AddField(
            model_name='accountledger',
            name='entry_type',
            field=models.CharField(choices=[('DEBIT', 'بدهکار'), ('CREDIT', 'بستانکار')], default='CREDIT', max_length=10, verbose_name='نوع گردش'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='accountledger',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='مبلغ'),
        ),
        migrations.AlterField(
            model_name='accountledger',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت'),
        ),
        migrations.AlterField(
            model_name='accountledger',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchange.currency', verbose_name='ارز'),
        ),
        migrations.AlterField(
            model_name='accountledger',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchange.customer', verbose_name='مشتری'),
        ),
        migrations.AlterField(
            model_name='accountledger',
            name='description',
            field=models.TextField(blank=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='code',
            field=models.CharField(max_length=10, verbose_name='کد ارز'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='name',
            field=models.CharField(max_length=50, verbose_name='نام ارز'),
        ),
        migrations.AlterField(
            model_name='custody',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='مقدار'),
        ),
        migrations.AlterField(
            model_name='custody',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت'),
        ),
        migrations.AlterField(
            model_name='custody',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchange.currency', verbose_name='ارز'),
        ),
        migrations.AlterField(
            model_name='custody',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchange.customer', verbose_name='مشتری'),
        ),
        migrations.AlterField(
            model_name='custody',
            name='description',
            field=models.TextField(blank=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='description',
            field=models.TextField(blank=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام مشتری'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='شماره تماس'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='description',
            field=models.TextField(blank=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='file',
            field=models.FileField(upload_to='receipts/', verbose_name='فایل رسید'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='exchange.transaction', verbose_name='معامله'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='مبلغ'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchange.customer', verbose_name='مشتری'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='from_currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_transactions', to='exchange.currency', verbose_name='ارز مبدا'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='from_wallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outgoing_transactions', to='exchange.wallet', verbose_name='کیف پول مبدا'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='rate',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='نرخ'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='to_currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_transactions', to='exchange.currency', verbose_name='ارز مقصد'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='to_wallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_transactions', to='exchange.wallet', verbose_name='کیف پول مقصد'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='tracking_number',
            field=models.CharField(max_length=100, unique=True, verbose_name='شماره معامله'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('BUY', 'خرید'), ('SELL', 'فروش'), ('EXCHANGE', 'چنج')], max_length=20, verbose_name='نوع معامله'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='description',
            field=models.TextField(blank=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام کیف پول'),
        ),
        migrations.AlterField(
            model_name='walletbalance',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='موجودی'),
        ),
        migrations.AlterField(
            model_name='walletbalance',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchange.currency', verbose_name='ارز'),
        ),
        migrations.AlterField(
            model_name='walletbalance',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchange.wallet', verbose_name='کیف پول'),
        ),
    ]
