# Generated by Django 6.0.7 on 2026-07-14 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0009_remove_customer_created_at_accountledger_entry_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerBankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100, verbose_name='نام بانک')),
                ('card_number', models.CharField(blank=True, max_length=30, verbose_name='شماره کارت')),
                ('account_number', models.CharField(blank=True, max_length=50, verbose_name='شماره حساب')),
                ('iban', models.CharField(blank=True, max_length=50, verbose_name='شماره شبا')),
                ('country', models.CharField(choices=[('IR', 'ایران'), ('TR', 'ترکیه')], max_length=2, verbose_name='کشور')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchange.customer', verbose_name='مشتری')),
            ],
            options={
                'verbose_name': 'حساب بانکی مشتری',
                'verbose_name_plural': 'حساب\u200cهای بانکی مشتریان',
            },
        ),
    ]
