# Generated by Django 6.0.7 on 2026-07-14 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0010_customerbankaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='destination_amount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=20, verbose_name='مبلغ مقصد'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='مبلغ مبدا'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت'),
        ),
    ]
