# Generated by Django 6.0.7 on 2026-07-14 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0011_transaction_destination_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountledger',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exchange.transaction', verbose_name='معامله'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='note',
            field=models.TextField(blank=True, verbose_name='توضیحات'),
        ),
    ]
