# Generated by Django 6.0.7 on 2026-07-18 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0012_accountledger_transaction_alter_transaction_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='receipt',
            field=models.FileField(blank=True, null=True, upload_to='receipts/', verbose_name='رسید'),
        ),
    ]
