# Generated by Django 6.0.7 on 2026-07-28 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0013_transaction_receipt'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy_rate', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='نرخ خرید')),
                ('sell_rate', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='نرخ فروش')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchange.currency', verbose_name='ارز')),
            ],
            options={
                'verbose_name': 'نرخ ارز',
                'verbose_name_plural': 'نرخ ارزها',
            },
        ),
    ]
